import React from "react";

const InternationalFlags = () => {
  return (
    <>
      <section className="margintop">
        <div
          className="container-fluid"
          style={{ backgroundColor: "#f9f3f3", padding: "50px 0px" }}
        >
          <div className="covid text-center">
            <h2 className="mt-2 h2-fs">
              International{" "}
              <span className="m-0 text-blue-color">accredited academy</span>
            </h2>
          </div>
          <div id="maindiv">
            <div id="div1">
              <span className="mx-2 flag flag-md flag-country-ad"></span>
              <span className="mx-2 flag flag-md flag-country-ae"></span>
              <span className="mx-2 flag flag-md flag-country-af"></span>
              <span className="mx-2 flag flag-md flag-country-ag"></span>
              <span className="mx-2 flag flag-md flag-country-ai"></span>
              <span className="mx-2 flag flag-md flag-country-am"></span>
              <span className="mx-2 flag flag-md flag-country-ao"></span>
              <span className="mx-2 flag flag-md flag-country-aq"></span>
              <span className="mx-2 flag flag-md flag-country-ar"></span>
              <span className="mx-2 flag flag-md flag-country-as"></span>
              <span className="mx-2 flag flag-md flag-country-at"></span>
              <span className="mx-2 flag flag-md flag-country-au"></span>
              <span className="mx-2 flag flag-md flag-country-aw"></span>
              <span className="mx-2 flag flag-md flag-country-ax"></span>
              <span className="mx-2 flag flag-md flag-country-az"></span>
              <span className="mx-2 flag flag-md flag-country-ba"></span>
              <span className="mx-2 flag flag-md flag-country-bb"></span>
              <span className="mx-2 flag flag-md flag-country-be"></span>
              <span className="mx-2 flag flag-md flag-country-bf"></span>
              <span className="mx-2 flag flag-md flag-country-bg"></span>
              <span className="mx-2 flag flag-md flag-country-bh"></span>
              <span className="mx-2 flag flag-md flag-country-bi"></span>
              <span className="mx-2 flag flag-md flag-country-bj"></span>
              <span className="mx-2 flag flag-md flag-country-bl"></span>
              <span className="mx-2 flag flag-md flag-country-bm"></span>
              <span className="mx-2 flag flag-md flag-country-bn"></span>
              <span className="mx-2 flag flag-md flag-country-bo"></span>
              <span className="mx-2 flag flag-md flag-country-bq"></span>
              <span className="mx-2 flag flag-md flag-country-br"></span>
              <span className="mx-2 flag flag-md flag-country-bs"></span>
              <span className="mx-2 flag flag-md flag-country-bt"></span>
              <span className="mx-2 flag flag-md flag-country-bv"></span>
              <span className="mx-2 flag flag-md flag-country-bw"></span>
              <span className="mx-2 flag flag-md flag-country-by"></span>
              <span className="mx-2 flag flag-md flag-country-bz"></span>
              <span className="mx-2 flag flag-md flag-country-ca"></span>
              <span className="mx-2 flag flag-md flag-country-cc"></span>
              <span className="mx-2 flag flag-md flag-country-cd"></span>
              <span className="mx-2 flag flag-md flag-country-cf"></span>
              <span className="mx-2 flag flag-md flag-country-cg"></span>
              <span className="mx-2 flag flag-md flag-country-ch"></span>
              <span className="mx-2 flag flag-md flag-country-ci"></span>
              <span className="mx-2 flag flag-md flag-country-ck"></span>
              <span className="mx-2 flag flag-md flag-country-cl"></span>
              <span className="mx-2 flag flag-md flag-country-cm"></span>
              <span className="mx-2 flag flag-md flag-country-cn"></span>
              <span className="mx-2 flag flag-md flag-country-co"></span>
              <span className="mx-2 flag flag-md flag-country-cr"></span>
              <span className="mx-2 flag flag-md flag-country-cu"></span>
              <span className="mx-2 flag flag-md flag-country-cv"></span>
              <span className="mx-2 flag flag-md flag-country-cw"></span>
              <span className="mx-2 flag flag-md flag-country-cx"></span>
              <span className="mx-2 flag flag-md flag-country-cy"></span>
              <span className="mx-2 flag flag-md flag-country-cz"></span>
              <span className="mx-2 flag flag-md flag-country-de"></span>
              <span className="mx-2 flag flag-md flag-country-dj"></span>
              <span className="mx-2 flag flag-md flag-country-dk"></span>
              <span className="mx-2 flag flag-md flag-country-dm"></span>
              <span className="mx-2 flag flag-md flag-country-do"></span>
              <span className="mx-2 flag flag-md flag-country-dz"></span>
              <span className="mx-2 flag flag-md flag-country-ec"></span>
              <span className="mx-2 flag flag-md flag-country-ee"></span>
              <span className="mx-2 flag flag-md flag-country-eg"></span>
              <span className="mx-2 flag flag-md flag-country-eh"></span>
              <span className="mx-2 flag flag-md flag-country-er"></span>
              <span className="mx-2 flag flag-md flag-country-es"></span>
              <span className="mx-2 flag flag-md flag-country-es-ct"></span>
              <span className="mx-2 flag flag-md flag-country-et"></span>
              <span className="mx-2 flag flag-md flag-country-eu"></span>
              <span className="mx-2 flag flag-md flag-country-fi"></span>
              <span className="mx-2 flag flag-md flag-country-fj"></span>
              <span className="mx-2 flag flag-md flag-country-fk"></span>
              <span className="mx-2 flag flag-md flag-country-fm"></span>
              <span className="mx-2 flag flag-md flag-country-fo"></span>
              <span className="mx-2 flag flag-md flag-country-fr"></span>
              <span className="mx-2 flag flag-md flag-country-ga"></span>
              <span className="mx-2 flag flag-md flag-country-gb"></span>
              <span className="mx-2 flag flag-md flag-country-gb-eng"></span>
              <span className="mx-2 flag flag-md flag-country-gb-nir"></span>
              <span className="mx-2 flag flag-md flag-country-gb-sct"></span>
              <span className="mx-2 flag flag-md flag-country-gb-wls"></span>
              <span className="mx-2 flag flag-md flag-country-gd"></span>
              <span className="mx-2 flag flag-md flag-country-ge"></span>
              <span className="mx-2 flag flag-md flag-country-gf"></span>
              <span className="mx-2 flag flag-md flag-country-gg"></span>
              <span className="mx-2 flag flag-md flag-country-gh"></span>
              <span className="mx-2 flag flag-md flag-country-gi"></span>
              <span className="mx-2 flag flag-md flag-country-gl"></span>
              <span className="mx-2 flag flag-md flag-country-gm"></span>
              <span className="mx-2 flag flag-md flag-country-gn"></span>
              <span className="mx-2 flag flag-md flag-country-gp"></span>
              <span className="mx-2 flag flag-md flag-country-gq"></span>
              <span className="mx-2 flag flag-md flag-country-gr"></span>
              <span className="mx-2 flag flag-md flag-country-gs"></span>
              <span className="mx-2 flag flag-md flag-country-gt"></span>
              <span className="mx-2 flag flag-md flag-country-gu"></span>
              <span className="mx-2 flag flag-md flag-country-gw"></span>
              <span className="mx-2 flag flag-md flag-country-gy"></span>
              <span className="mx-2 flag flag-md flag-country-hk"></span>
              <span className="mx-2 flag flag-md flag-country-hm"></span>
              <span className="mx-2 flag flag-md flag-country-hn"></span>
              <span className="mx-2 flag flag-md flag-country-hr"></span>
              <span className="mx-2 flag flag-md flag-country-ht"></span>
              <span className="mx-2 flag flag-md flag-country-hu"></span>
              <span className="mx-2 flag flag-md flag-country-id"></span>
              <span className="mx-2 flag flag-md flag-country-ie"></span>
              <span className="mx-2 flag flag-md flag-country-il"></span>
              <span className="mx-2 flag flag-md flag-country-im"></span>
              <span className="mx-2 flag flag-md flag-country-in"></span>
              <span className="mx-2 flag flag-md flag-country-io"></span>
              <span className="mx-2 flag flag-md flag-country-iq"></span>
              <span className="mx-2 flag flag-md flag-country-ir"></span>
              <span className="mx-2 flag flag-md flag-country-is"></span>
              <span className="mx-2 flag flag-md flag-country-it"></span>
              <span className="mx-2 flag flag-md flag-country-je"></span>
              <span className="mx-2 flag flag-md flag-country-jm"></span>
              <span className="mx-2 flag flag-md flag-country-jo"></span>
              <span className="mx-2 flag flag-md flag-country-jp"></span>
              <span className="mx-2 flag flag-md flag-country-ke"></span>
              <span className="mx-2 flag flag-md flag-country-kg"></span>
              <span className="mx-2 flag flag-md flag-country-kh"></span>
              <span className="mx-2 flag flag-md flag-country-ki"></span>
              <span className="mx-2 flag flag-md flag-country-km"></span>
              <span className="mx-2 flag flag-md flag-country-kn"></span>
              <span className="mx-2 flag flag-md flag-country-kp"></span>
              <span className="mx-2 flag flag-md flag-country-kr"></span>
              <span className="mx-2 flag flag-md flag-country-kw"></span>
              <span className="mx-2 flag flag-md flag-country-ky"></span>
              <span className="mx-2 flag flag-md flag-country-kz"></span>
              <span className="mx-2 flag flag-md flag-country-la"></span>
              <span className="mx-2 flag flag-md flag-country-lb"></span>
              <span className="mx-2 flag flag-md flag-country-lc"></span>
              <span className="mx-2 flag flag-md flag-country-li"></span>
              <span className="mx-2 flag flag-md flag-country-lk"></span>
              <span className="mx-2 flag flag-md flag-country-lr"></span>
              <span className="mx-2 flag flag-md flag-country-ls"></span>
              <span className="mx-2 flag flag-md flag-country-lt"></span>
              <span className="mx-2 flag flag-md flag-country-lu"></span>
              <span className="mx-2 flag flag-md flag-country-lv"></span>
              <span className="mx-2 flag flag-md flag-country-ly"></span>
              <span className="mx-2 flag flag-md flag-country-ma"></span>
              <span className="mx-2 flag flag-md flag-country-mc"></span>
              <span className="mx-2 flag flag-md flag-country-md"></span>
              <span className="mx-2 flag flag-md flag-country-me"></span>
              <span className="mx-2 flag flag-md flag-country-mf"></span>
              <span className="mx-2 flag flag-md flag-country-mg"></span>
              <span className="mx-2 flag flag-md flag-country-mh"></span>
              <span className="mx-2 flag flag-md flag-country-mk"></span>
              <span className="mx-2 flag flag-md flag-country-ml"></span>
              <span className="mx-2 flag flag-md flag-country-mm"></span>
              <span className="mx-2 flag flag-md flag-country-mn"></span>
              <span className="mx-2 flag flag-md flag-country-mo"></span>
              <span className="mx-2 flag flag-md flag-country-mp"></span>
              <span className="mx-2 flag flag-md flag-country-mq"></span>
              <span className="mx-2 flag flag-md flag-country-mr"></span>
              <span className="mx-2 flag flag-md flag-country-ms"></span>
              <span className="mx-2 flag flag-md flag-country-mt"></span>
              <span className="mx-2 flag flag-md flag-country-mu"></span>
              <span className="mx-2 flag flag-md flag-country-mv"></span>
              <span className="mx-2 flag flag-md flag-country-mw"></span>
              <span className="mx-2 flag flag-md flag-country-mx"></span>
              <span className="mx-2 flag flag-md flag-country-my"></span>
              <span className="mx-2 flag flag-md flag-country-mz"></span>
              <span className="mx-2 flag flag-md flag-country-na"></span>
              <span className="mx-2 flag flag-md flag-country-nc"></span>
              <span className="mx-2 flag flag-md flag-country-ne"></span>
              <span className="mx-2 flag flag-md flag-country-nf"></span>
              <span className="mx-2 flag flag-md flag-country-ng"></span>
              <span className="mx-2 flag flag-md flag-country-ni"></span>
              <span className="mx-2 flag flag-md flag-country-no"></span>
              <span className="mx-2 flag flag-md flag-country-np"></span>
              <span className="mx-2 flag flag-md flag-country-nr"></span>
              <span className="mx-2 flag flag-md flag-country-nu"></span>
              <span className="mx-2 flag flag-md flag-country-nz"></span>
              <span className="mx-2 flag flag-md flag-country-om"></span>
              <span className="mx-2 flag flag-md flag-country-pa"></span>
              <span className="mx-2 flag flag-md flag-country-pe"></span>
              <span className="mx-2 flag flag-md flag-country-pf"></span>
              <span className="mx-2 flag flag-md flag-country-pg"></span>
              <span className="mx-2 flag flag-md flag-country-ph"></span>
              <span className="mx-2 flag flag-md flag-country-pk"></span>
              <span className="mx-2 flag flag-md flag-country-pl"></span>
              <span className="mx-2 flag flag-md flag-country-pm"></span>
              <span className="mx-2 flag flag-md flag-country-pn"></span>
              <span className="mx-2 flag flag-md flag-country-pr"></span>
              <span className="mx-2 flag flag-md flag-country-ps"></span>
              <span className="mx-2 flag flag-md flag-country-pt"></span>
              <span className="mx-2 flag flag-md flag-country-pw"></span>
              <span className="mx-2 flag flag-md flag-country-py"></span>
              <span className="mx-2 flag flag-md flag-country-qa"></span>
              <span className="mx-2 flag flag-md flag-country-re"></span>
              <span className="mx-2 flag flag-md flag-country-ro"></span>
              <span className="mx-2 flag flag-md flag-country-rs"></span>
              <span className="mx-2 flag flag-md flag-country-ru"></span>
              <span className="mx-2 flag flag-md flag-country-rw"></span>
              <span className="mx-2 flag flag-md flag-country-sa"></span>
              <span className="mx-2 flag flag-md flag-country-sb"></span>
              <span className="mx-2 flag flag-md flag-country-sc"></span>
              <span className="mx-2 flag flag-md flag-country-sd"></span>
              <span className="mx-2 flag flag-md flag-country-se"></span>
              <span className="mx-2 flag flag-md flag-country-sg"></span>
              <span className="mx-2 flag flag-md flag-country-sh"></span>
              <span className="mx-2 flag flag-md flag-country-si"></span>
              <span className="mx-2 flag flag-md flag-country-sj"></span>
              <span className="mx-2 flag flag-md flag-country-sk"></span>
              <span className="mx-2 flag flag-md flag-country-sl"></span>
              <span className="mx-2 flag flag-md flag-country-sm"></span>
              <span className="mx-2 flag flag-md flag-country-sn"></span>
              <span className="mx-2 flag flag-md flag-country-so"></span>
              <span className="mx-2 flag flag-md flag-country-sr"></span>
              <span className="mx-2 flag flag-md flag-country-ss"></span>
              <span className="mx-2 flag flag-md flag-country-st"></span>
              <span className="mx-2 flag flag-md flag-country-sv"></span>
              <span className="mx-2 flag flag-md flag-country-sx"></span>
              <span className="mx-2 flag flag-md flag-country-sy"></span>
              <span className="mx-2 flag flag-md flag-country-sz"></span>
              <span className="mx-2 flag flag-md flag-country-tc"></span>
              <span className="mx-2 flag flag-md flag-country-td"></span>
              <span className="mx-2 flag flag-md flag-country-tf"></span>
              <span className="mx-2 flag flag-md flag-country-tg"></span>
              <span className="mx-2 flag flag-md flag-country-th"></span>
              <span className="mx-2 flag flag-md flag-country-tj"></span>
              <span className="mx-2 flag flag-md flag-country-tk"></span>
              <span className="mx-2 flag flag-md flag-country-tl"></span>
              <span className="mx-2 flag flag-md flag-country-tm"></span>
              <span className="mx-2 flag flag-md flag-country-tn"></span>
              <span className="mx-2 flag flag-md flag-country-to"></span>
              <span className="mx-2 flag flag-md flag-country-tr"></span>
              <span className="mx-2 flag flag-md flag-country-tt"></span>
              <span className="mx-2 flag flag-md flag-country-tv"></span>
              <span className="mx-2 flag flag-md flag-country-tz"></span>
              <span className="mx-2 flag flag-md flag-country-ua"></span>
              <span className="mx-2 flag flag-md flag-country-ug"></span>
              <span className="mx-2 flag flag-md flag-country-um"></span>
              <span className="mx-2 flag flag-md flag-country-un"></span>
              <span className="mx-2 flag flag-md flag-country-us"></span>
              <span className="mx-2 flag flag-md flag-country-uy"></span>
              <span className="mx-2 flag flag-md flag-country-uz"></span>
              <span className="mx-2 flag flag-md flag-country-va"></span>
              <span className="mx-2 flag flag-md flag-country-vc"></span>
              <span className="mx-2 flag flag-md flag-country-ve"></span>
              <span className="mx-2 flag flag-md flag-country-vg"></span>
              <span className="mx-2 flag flag-md flag-country-vi"></span>
              <span className="mx-2 flag flag-md flag-country-vn"></span>
              <span className="mx-2 flag flag-md flag-country-vu"></span>
              <span className="mx-2 flag flag-md flag-country-wf"></span>
              <span className="mx-2 flag flag-md flag-country-ws"></span>
              <span className="mx-2 flag flag-md flag-country-ye"></span>
              <span className="mx-2 flag flag-md flag-country-za"></span>
              <span className="mx-2 flag flag-md flag-country-zm"></span>
              <span className="mx-2 flag flag-md flag-country-zw"></span>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export default InternationalFlags;
